site_name: T3CO 
site_description: Transportation Technology Total Cost of Ownership
repo_url: https://github.com/NatLabRockies/T3CO
edit_uri: https://github.com/NatLabRockies/T3CO/tree/main/docs
site_author: Harish Panneer Selvam 

extra:
  analytics:
    provider: google
    property: G-QDQ7VBSCE0
  feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  generator: false

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            heading_level: 2
            members_order: source
            docstring_style: google

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

theme:
  name: material
  favicon: t3co_logo.svg
  highlightjs: true
  hljs_languages:
    - python
    - yaml
  features:
    - search.highlight
    - content.action.view
    - search.suggest
    - content.code.copy
    - navigation.path
    - content.tooltips
    - navigation.path
    - navigation.sections
    - toc.integrate 
    - navigation.top
    - header.autohide

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
    
nav:
    - Home: index.md
    - What's New in 2.0: whats_new.md
    - Installation: installation.md
    - Quick Start: quick_start.md
    - Overview: T3CO_Overview.md
    - Costs and Features: pages/cost_and_tool_features.md
    - Inputs: 
      - Vehicle: pages/vehicle_inputs_descriptions.md
      - Scenario: pages/scenario_inputs_descriptions.md
      - Config: pages/config_inputs_descriptions.md
    - Outputs:
      - Ledger: pages/ledger_outputs_descriptions.md
    - Visualization: pages/visualization.md
    - API Reference:
      - Input Data Module:
        - Vehicle: pages/api/vehicle.md
        - Scenario: pages/api/scenario.md
        - Config: pages/api/config.md  
      - Energy Module:
        - Energy: pages/api/energy.md
        - FASTSim Wrapper: pages/api/fastsim_wrapper.md
      - Cost Module:
        - Capital Costs: pages/api/capital_costs.md
        - Operating Costs: pages/api/operating_costs.md
        - Opportunity Costs: pages/api/opportunity_costs.md
      - TCO Module:
        - TCO Calc Per Year: pages/api/tcocalc.md
        - Ledger: pages/api/ledger.md
      - CLI Module:
        - Sweep: pages/api/sweep.md
      - Visualization Module:
        - Charts: pages/api/charts.md
      - Utility Module:
        - Demo Files Installer: pages/api/demo_files_installer.md
        - Print Class Objects: pages/api/print_class_objects.md

