site_name: T3CO 
site_description: Transportation Technology Total Cost of Ownership
repo_url: https://github.com/NREL/T3CO
edit_uri: https://github.com/NREL/T3CO/tree/main/docs
site_author: Harish Panneer Selvam 

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_if_no_docstring: true
            docstring_options:
              ignore_init_summary: false
            merge_init_into_class: false
            heading_level: 2
            show_root_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_root_toc_entry: true 
            annotations_path: source
            show_signature: true
            separate_signature: false
            show_signature_annotations: true
            unwrap_annotated: true








markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


theme:
  name: material
  favicon: t3co_logo.svg
  highlightjs: true
  hljs_languages:
    - python
    - yaml
  features:
    - search.highlight
    - content.action.view
    - search.suggest
    - content.code.copy
    - navigation.path
    - content.tooltips


  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye

nav:
    - Home: index.md
    - Installation: installation.md
    - Quick Start: quick_start.md
    - Overview: T3CO_Overview.md
    - Inputs: 
      - Vehicle: vehicle_inputs_descriptions.md
      - Scenario: scenario_inputs_descriptions.md
      - Config: config_inputs_descriptions.md
    - Results:
      - Outputs: t3co_outputs_descriptions.md
    - Code Reference:
      - CodeFlow: CodeFlow.md      
      - T3CO Modules: 
        - Sweep: sweep.md  
        - Run Modules:
          - Run Scenario: run_scenario.md
          - Generate Inputs: generateinputs.md
          - Global Variables: Global.md        
        - TCO Modules:
          - Opportunity Costs: opportunity_cost.md
          - TCO Calculations: tcocalc.md
          - TCO Analysis: tco_analysis.md
          - TCO Stock and Emissions: tco_stock_emissions.md
        - Multi Objective Optimization Module:
          - MOO: moo.md
        - Objectives Modules: 
          - Acceleration Test: accel.md
          - Gradeability Test: gradeability.md
          - Fuel Economy: fueleconomy.md