[project]
name = "t3co"
version = "2.0.0"
dynamic = ["dependencies"]
description = "NREL's Transportation Technology Total Cost of Ownership tool"
readme = "README.md"
license = "BSD-3-Clause"
authors = [
    {name = "Harish Panneer Selvam", email = "Harish.PanneerSelvam@nrel.gov"},
    {name = "Alicia Birky", email = "Alicia.Birky@nrel.gov"},
]
maintainers = [{name = "NREL-AVCI", email = "t3co@nrel.gov"}]
keywords = ["tco", "vehicle-cost", "total-cost", "vehicle-simulation", "total-cost-of-ownership"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Education",
    "Topic :: Scientific/Engineering",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",    
]
requires-python = ">=3.9,<4"

[tool.poetry.dependencies]
python = ">=3.9,<4"
pandas = "^2.3.0"
numpy = "^1.26.0"
scipy = [
    {version = "^1.11.0", python = ">=3.9,<3.10"},
    {version = "^1.13.0", python = ">=3.10"}
]
fastsim = { version = "^2.1.1", optional = true, python = ">=3.9,<3.11" }

[project.optional-dependencies]
fastsim = ["fastsim", "pymoo"]
dev = ["pytest", "pytest-mock", "fastsim", "pymoo","ruff"]

[project.scripts]
install_t3co_demo_inputs = "t3co.utils.demo_inputs_installer:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [{include = "t3co", from = "src"}]

[project.urls]
Homepage = "https://www.nrel.gov/transportation/t3co.html"
Documentation = "https://pages.github.nrel.gov/AVCI/T3CO"
Repository = "https://github.nrel.gov/AVCI/T3CO"
"Bug Tracker" = "https://github.nrel.gov/AVCI/T3CO/issues"